; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
framework = arduino
platform_packages = 
	framework-arduino @ https://github.com/espressif/arduino-esp32/archive/refs/tags/3.1.0.zip
lib_ldf_mode = chain
lib_deps = 
	gurusr/SmallRTC@^2.4.7
	lucadentella/TOTP library@^1.1.0
	zinggjm/GxEPD2@^1.6.2
	tzapu/WiFiManager@^2.0.17
	arduino-libraries/NTPClient@^3.2.1
	bblanchon/ArduinoJson@^7.2.2
	https://github.com/lewisxhe/BMA423_Library
	https://github.com/arduino-libraries/Arduino_JSON.git
	https://github.com/dirkx/Arduino-Base32-Decode
build_flags = 
	-Wno-deprecated-declarations
	-Wno-maybe-uninitialized
	-fno-if-conversion
	-Wno-format
	-Wno-stringop-truncation
	-Wno-unused-value
	-Wno-use-after-free
	-Wno-unused-variable
	-Wno-unused-function
	-D BLE_42_FEATURE_SUPPORT=TRUE
	-D BLE_50_FEATURE_SUPPORT=TRUE
board_upload.offset_address = 0x20000
board_build.partitions = res/huge_app.csv
board_build.filesystem = littlefs
monitor_speed = 921600

[env:Watchy2]
board = watchy
upload_speed = 921600
build_flags = 
	${env.build_flags}
	-D ARDUINO_WATCHY_V20=TRUE
	-D LITTLEFS_SPIFFS_COMPAT=1
	-D CONFIG_LITTLEFS_FOR_IDF_SPIFFS_COMPAT_MODE=y
